// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID            pgtype.UUID        `json:"id"`
	WorkspaceName string             `json:"workspace_name"`
	Description   string             `json:"description"`
	UserID        pgtype.Text        `json:"user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceMember struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.Text        `json:"user_id"`
	WorkspaceID pgtype.Text        `json:"workspace_id"`
	UserRole    string             `json:"user_role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
