// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IntegrationTask struct {
	ID             pgtype.UUID        `json:"id"`
	Provider       string             `json:"provider"`
	ResourceType   string             `json:"resource_type"`
	ExternalID     string             `json:"external_id"`
	RepositoryName string             `json:"repository_name"`
	IssueNumber    int32              `json:"issue_number"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Status         string             `json:"status"`
	AssigneeID     pgtype.UUID        `json:"assignee_id"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Message struct {
	ID         pgtype.UUID        `json:"id"`
	SenderID   pgtype.UUID        `json:"sender_id"`
	ReceiverID pgtype.UUID        `json:"receiver_id"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Subscription struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	StripePriceID        string             `json:"stripe_price_id"`
	Status               string             `json:"status"`
	Plan                 string             `json:"plan"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceName    string             `json:"workspace_name"`
	Description      string             `json:"description"`
	UserID           pgtype.UUID        `json:"user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
}

type WorkspaceMember struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserRole    string             `json:"user_role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
