// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error)
	CountUserWorkspaces(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountWorkspaceProjects(ctx context.Context, workspaceID pgtype.UUID) (int64, error)
	CreateIntegrationTask(ctx context.Context, arg CreateIntegrationTaskParams) (IntegrationTask, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectIntegration(ctx context.Context, arg CreateProjectIntegrationParams) (ProjectIntegration, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeactivateSubscription(ctx context.Context, stripeSubscriptionID string) (Subscription, error)
	DeleteMemberFromWorkspace(ctx context.Context, arg DeleteMemberFromWorkspaceParams) error
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	DeleteTask(ctx context.Context, id pgtype.UUID) error
	DeleteWorkspace(ctx context.Context, arg DeleteWorkspaceParams) error
	GetMemberFromWorkspace(ctx context.Context, arg GetMemberFromWorkspaceParams) (WorkspaceMember, error)
	GetMessagesBetweenUsers(ctx context.Context, arg GetMessagesBetweenUsersParams) ([]GetMessagesBetweenUsersRow, error)
	GetProjectById(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProjectIntegrationByProjectID(ctx context.Context, projectID pgtype.UUID) (ProjectIntegration, error)
	GetProjectIntegrationByRepository(ctx context.Context, arg GetProjectIntegrationByRepositoryParams) (ProjectIntegration, error)
	GetProjectTasks(ctx context.Context, arg GetProjectTasksParams) ([]GetProjectTasksRow, error)
	GetSubscriptionByStripeSubscription(ctx context.Context, stripeSubscriptionID string) (Subscription, error)
	GetTaskById(ctx context.Context, id pgtype.UUID) (Task, error)
	GetUserActiveProSubscription(ctx context.Context, userID pgtype.UUID) (Subscription, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByStripeCustomerID(ctx context.Context, stripeCustomerID pgtype.Text) (User, error)
	GetUserWorkspaceByID(ctx context.Context, arg GetUserWorkspaceByIDParams) (Workspace, error)
	GetUserWorkspaces(ctx context.Context, arg GetUserWorkspacesParams) ([]GetUserWorkspacesRow, error)
	GetWorkspaceActiveSubscription(ctx context.Context, workspaceID pgtype.UUID) (Subscription, error)
	GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error)
	GetWorkspaceMembers(ctx context.Context, arg GetWorkspaceMembersParams) ([]GetWorkspaceMembersRow, error)
	GetWorkspaceProjects(ctx context.Context, arg GetWorkspaceProjectsParams) ([]GetWorkspaceProjectsRow, error)
	Register(ctx context.Context, arg RegisterParams) (User, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectIntegrationWebhookSecret(ctx context.Context, arg UpdateProjectIntegrationWebhookSecretParams) (ProjectIntegration, error)
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpdateWorkspaceStripeCustomer(ctx context.Context, arg UpdateWorkspaceStripeCustomerParams) (Workspace, error)
}

var _ Querier = (*Queries)(nil)
