// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id string) (User, error)
	GetUserWorkspace(ctx context.Context, userID pgtype.Text) (Workspace, error)
	Register(ctx context.Context, arg RegisterParams) (User, error)
}

var _ Querier = (*Queries)(nil)
