// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :one
INSERT INTO workspace_members (id, user_id, workspace_id, user_role)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, workspace_id, user_role, created_at
`

type AddWorkspaceMemberParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserRole    string      `json:"user_role"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, addWorkspaceMember,
		arg.ID,
		arg.UserID,
		arg.WorkspaceID,
		arg.UserRole,
	)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.UserRole,
		&i.CreatedAt,
	)
	return i, err
}

const countUserWorkspaces = `-- name: CountUserWorkspaces :one
SELECT COUNT(*)
FROM workspaces
WHERE user_id = $1
`

func (q *Queries) CountUserWorkspaces(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserWorkspaces, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaceProjects = `-- name: CountWorkspaceProjects :one
SELECT COUNT(*)
FROM projects
WHERE workspace_id = $1
`

func (q *Queries) CountWorkspaceProjects(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceProjects, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIntegrationTask = `-- name: CreateIntegrationTask :one
INSERT INTO integration_tasks (id,
                               provider,
                               resource_type,
                               external_id,
                               repository_name,
                               issue_number,
                               title,
                               description,
                               status,
                               assignee_id,
                               payload)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11) RETURNING id, provider, resource_type, external_id, repository_name, issue_number, title, description, status, assignee_id, payload, created_at, updated_at
`

type CreateIntegrationTaskParams struct {
	ID             pgtype.UUID `json:"id"`
	Provider       string      `json:"provider"`
	ResourceType   string      `json:"resource_type"`
	ExternalID     string      `json:"external_id"`
	RepositoryName string      `json:"repository_name"`
	IssueNumber    int32       `json:"issue_number"`
	Title          string      `json:"title"`
	Description    pgtype.Text `json:"description"`
	Status         string      `json:"status"`
	AssigneeID     pgtype.UUID `json:"assignee_id"`
	Payload        []byte      `json:"payload"`
}

func (q *Queries) CreateIntegrationTask(ctx context.Context, arg CreateIntegrationTaskParams) (IntegrationTask, error) {
	row := q.db.QueryRow(ctx, createIntegrationTask,
		arg.ID,
		arg.Provider,
		arg.ResourceType,
		arg.ExternalID,
		arg.RepositoryName,
		arg.IssueNumber,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.AssigneeID,
		arg.Payload,
	)
	var i IntegrationTask
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ResourceType,
		&i.ExternalID,
		&i.RepositoryName,
		&i.IssueNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeID,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, sender_id, receiver_id, content)
VALUES ($1, $2, $3, $4) RETURNING id, sender_id, receiver_id, content, created_at
`

type CreateMessageParams struct {
	ID         pgtype.UUID `json:"id"`
	SenderID   pgtype.UUID `json:"sender_id"`
	ReceiverID pgtype.UUID `json:"receiver_id"`
	Content    string      `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.SenderID,
		arg.ReceiverID,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, description, workspace_id)
VALUES ($1, $2, $3, $4) RETURNING id, name, description, workspace_id, created_at, updated_at
`

type CreateProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.WorkspaceID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (id,
                           workspace_id,
                           stripe_subscription_id,
                           stripe_price_id,
                           status,
                           plan,
                           current_period_start,
                           current_period_end)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, workspace_id, stripe_subscription_id, stripe_price_id, status, plan, current_period_start, current_period_end, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	StripePriceID        string             `json:"stripe_price_id"`
	Status               string             `json:"status"`
	Plan                 string             `json:"plan"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ID,
		arg.WorkspaceID,
		arg.StripeSubscriptionID,
		arg.StripePriceID,
		arg.Status,
		arg.Plan,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Status,
		&i.Plan,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, name, description, start_date, end_date, status, priority, project_id, assignee_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, name, description, start_date, end_date, status, priority, project_id, assignee_id, created_at, updated_at
`

type CreateTaskParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	Status      string      `json:"status"`
	Priority    string      `json:"priority"`
	ProjectID   pgtype.UUID `json:"project_id"`
	AssigneeID  pgtype.UUID `json:"assignee_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.Priority,
		arg.ProjectID,
		arg.AssigneeID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Priority,
		&i.ProjectID,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, workspace_name, description, user_id)
VALUES ($1, $2, $3, $4) RETURNING id, workspace_name, description, user_id, created_at, updated_at, stripe_customer_id
`

type CreateWorkspaceParams struct {
	ID            pgtype.UUID `json:"id"`
	WorkspaceName string      `json:"workspace_name"`
	Description   string      `json:"description"`
	UserID        pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.WorkspaceName,
		arg.Description,
		arg.UserID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.WorkspaceName,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StripeCustomerID,
	)
	return i, err
}

const deactivateSubscription = `-- name: DeactivateSubscription :one
UPDATE subscriptions
SET status     = 'INACTIVE',
    updated_at = NOW()
WHERE stripe_subscription_id = $1 RETURNING id, workspace_id, stripe_subscription_id, stripe_price_id, status, plan, current_period_start, current_period_end, created_at, updated_at
`

func (q *Queries) DeactivateSubscription(ctx context.Context, stripeSubscriptionID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, deactivateSubscription, stripeSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Status,
		&i.Plan,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMemberFromWorkspace = `-- name: DeleteMemberFromWorkspace :exec
DELETE
FROM workspace_members
WHERE user_id = $1
  AND workspace_id = $2
`

type DeleteMemberFromWorkspaceParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteMemberFromWorkspace(ctx context.Context, arg DeleteMemberFromWorkspaceParams) error {
	_, err := q.db.Exec(ctx, deleteMemberFromWorkspace, arg.UserID, arg.WorkspaceID)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE
FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE
FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE
FROM workspaces
WHERE id = $1
  AND user_id = $2
`

type DeleteWorkspaceParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteWorkspace(ctx context.Context, arg DeleteWorkspaceParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, arg.ID, arg.UserID)
	return err
}

const getMemberFromWorkspace = `-- name: GetMemberFromWorkspace :one
SELECT id, user_id, workspace_id, user_role, created_at
FROM workspace_members
WHERE user_id = $1
  AND workspace_id = $2
`

type GetMemberFromWorkspaceParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetMemberFromWorkspace(ctx context.Context, arg GetMemberFromWorkspaceParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getMemberFromWorkspace, arg.UserID, arg.WorkspaceID)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.UserRole,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesBetweenUsers = `-- name: GetMessagesBetweenUsers :many
SELECT count(*) OVER () AS total_count, id,
       sender_id,
       receiver_id,
       content,
       created_at
FROM messages
WHERE (sender_id = $1 AND receiver_id = $2)
   OR (sender_id = $2 AND receiver_id = $1)
ORDER BY created_at DESC LIMIT $3
OFFSET $4
`

type GetMessagesBetweenUsersParams struct {
	SenderID   pgtype.UUID `json:"sender_id"`
	ReceiverID pgtype.UUID `json:"receiver_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type GetMessagesBetweenUsersRow struct {
	TotalCount int64              `json:"total_count"`
	ID         pgtype.UUID        `json:"id"`
	SenderID   pgtype.UUID        `json:"sender_id"`
	ReceiverID pgtype.UUID        `json:"receiver_id"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMessagesBetweenUsers(ctx context.Context, arg GetMessagesBetweenUsersParams) ([]GetMessagesBetweenUsersRow, error) {
	rows, err := q.db.Query(ctx, getMessagesBetweenUsers,
		arg.SenderID,
		arg.ReceiverID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesBetweenUsersRow
	for rows.Next() {
		var i GetMessagesBetweenUsersRow
		if err := rows.Scan(
			&i.TotalCount,
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectById = `-- name: GetProjectById :one
SELECT id, name, description, workspace_id, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectById(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectById, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectTasks = `-- name: GetProjectTasks :many
SELECT count(*) OVER () AS total_count, id,
       name,
       description,
       start_date,
       end_date,
       status,
       priority,
       project_id,
       assignee_id,
       created_at,
       updated_at
FROM tasks
WHERE project_id = $1
ORDER BY created_at DESC LIMIT $2
OFFSET $3
`

type GetProjectTasksParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type GetProjectTasksRow struct {
	TotalCount  int64              `json:"total_count"`
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProjectTasks(ctx context.Context, arg GetProjectTasksParams) ([]GetProjectTasksRow, error) {
	rows, err := q.db.Query(ctx, getProjectTasks, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectTasksRow
	for rows.Next() {
		var i GetProjectTasksRow
		if err := rows.Scan(
			&i.TotalCount,
			&i.ID,
			&i.Name,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.Priority,
			&i.ProjectID,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionByStripeSubscription = `-- name: GetSubscriptionByStripeSubscription :one
SELECT id, workspace_id, stripe_subscription_id, stripe_price_id, status, plan, current_period_start, current_period_end, created_at, updated_at
FROM subscriptions
WHERE stripe_subscription_id = $1
`

func (q *Queries) GetSubscriptionByStripeSubscription(ctx context.Context, stripeSubscriptionID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByStripeSubscription, stripeSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Status,
		&i.Plan,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskById = `-- name: GetTaskById :one
SELECT id, name, description, start_date, end_date, status, priority, project_id, assignee_id, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskById(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskById, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Priority,
		&i.ProjectID,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserActiveProSubscription = `-- name: GetUserActiveProSubscription :one
SELECT s.id, s.workspace_id, s.stripe_subscription_id, s.stripe_price_id, s.status, s.plan, s.current_period_start, s.current_period_end, s.created_at, s.updated_at
FROM subscriptions s
         JOIN workspaces w ON w.id = s.workspace_id
WHERE w.user_id = $1
  AND s.status = 'ACTIVE'
  AND s.plan = 'PRO' LIMIT 1
`

func (q *Queries) GetUserActiveProSubscription(ctx context.Context, userID pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getUserActiveProSubscription, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Status,
		&i.Plan,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, password, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, first_name, last_name, email, password, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByStripeCustomerID = `-- name: GetUserByStripeCustomerID :one
SELECT u.id, u.first_name, u.last_name, u.email, u.password, u.created_at, u.updated_at
FROM users u
         JOIN workspaces w ON w.user_id = u.id
WHERE w.stripe_customer_id = $1 LIMIT 1
`

func (q *Queries) GetUserByStripeCustomerID(ctx context.Context, stripeCustomerID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByStripeCustomerID, stripeCustomerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWorkspaceByID = `-- name: GetUserWorkspaceByID :one
SELECT id, workspace_name, description, user_id, created_at, updated_at, stripe_customer_id
FROM workspaces
WHERE user_id = $1
  AND id = $2
`

type GetUserWorkspaceByIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) GetUserWorkspaceByID(ctx context.Context, arg GetUserWorkspaceByIDParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getUserWorkspaceByID, arg.UserID, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.WorkspaceName,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StripeCustomerID,
	)
	return i, err
}

const getUserWorkspaces = `-- name: GetUserWorkspaces :many
SELECT count(*) OVER () AS total_count, id,
       workspace_name,
       description,
       user_id,
       created_at,
       updated_at
FROM workspaces
WHERE user_id = $1
ORDER BY created_at DESC LIMIT $2
OFFSET $3
`

type GetUserWorkspacesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetUserWorkspacesRow struct {
	TotalCount    int64              `json:"total_count"`
	ID            pgtype.UUID        `json:"id"`
	WorkspaceName string             `json:"workspace_name"`
	Description   string             `json:"description"`
	UserID        pgtype.UUID        `json:"user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserWorkspaces(ctx context.Context, arg GetUserWorkspacesParams) ([]GetUserWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, getUserWorkspaces, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWorkspacesRow
	for rows.Next() {
		var i GetUserWorkspacesRow
		if err := rows.Scan(
			&i.TotalCount,
			&i.ID,
			&i.WorkspaceName,
			&i.Description,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceActiveSubscription = `-- name: GetWorkspaceActiveSubscription :one
SELECT id, workspace_id, stripe_subscription_id, stripe_price_id, status, plan, current_period_start, current_period_end, created_at, updated_at
FROM subscriptions
WHERE workspace_id = $1
  AND status = 'ACTIVE' LIMIT 1
`

func (q *Queries) GetWorkspaceActiveSubscription(ctx context.Context, workspaceID pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getWorkspaceActiveSubscription, workspaceID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Status,
		&i.Plan,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, workspace_name, description, user_id, created_at, updated_at, stripe_customer_id
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.WorkspaceName,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StripeCustomerID,
	)
	return i, err
}

const getWorkspaceMembers = `-- name: GetWorkspaceMembers :many
SELECT count(*)         OVER () AS total_count, wm.id AS member_id,
       wm.workspace_id,
       wm.user_role,
       wm.created_at AS member_created_at,
       u.id::uuid       AS user_id, u.first_name,
       u.last_name,
       u.email,
       u.created_at,
       u.updated_at
FROM workspace_members wm
         JOIN users u ON u.id::uuid = wm.user_id::uuid
WHERE wm.workspace_id = $1
ORDER BY wm.created_at DESC
    LIMIT $2
OFFSET $3
`

type GetWorkspaceMembersParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

type GetWorkspaceMembersRow struct {
	TotalCount      int64              `json:"total_count"`
	MemberID        pgtype.UUID        `json:"member_id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	UserRole        string             `json:"user_role"`
	MemberCreatedAt pgtype.Timestamptz `json:"member_created_at"`
	UserID          pgtype.UUID        `json:"user_id"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Email           string             `json:"email"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWorkspaceMembers(ctx context.Context, arg GetWorkspaceMembersParams) ([]GetWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaceMembers, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkspaceMembersRow
	for rows.Next() {
		var i GetWorkspaceMembersRow
		if err := rows.Scan(
			&i.TotalCount,
			&i.MemberID,
			&i.WorkspaceID,
			&i.UserRole,
			&i.MemberCreatedAt,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceProjects = `-- name: GetWorkspaceProjects :many
SELECT count(*) OVER () AS total_count, id,
       name,
       description,
       workspace_id,
       created_at,
       updated_at
FROM projects
WHERE workspace_id = $1
ORDER BY created_at DESC LIMIT $2
OFFSET $3
`

type GetWorkspaceProjectsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

type GetWorkspaceProjectsRow struct {
	TotalCount  int64              `json:"total_count"`
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWorkspaceProjects(ctx context.Context, arg GetWorkspaceProjectsParams) ([]GetWorkspaceProjectsRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaceProjects, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkspaceProjectsRow
	for rows.Next() {
		var i GetWorkspaceProjectsRow
		if err := rows.Scan(
			&i.TotalCount,
			&i.ID,
			&i.Name,
			&i.Description,
			&i.WorkspaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const register = `-- name: Register :one
INSERT INTO users (id, first_name, last_name, email, password)
VALUES ($1, $2, $3, $4, $5) RETURNING id, first_name, last_name, email, password, created_at, updated_at
`

type RegisterParams struct {
	ID        pgtype.UUID `json:"id"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Email     string      `json:"email"`
	Password  string      `json:"password"`
}

func (q *Queries) Register(ctx context.Context, arg RegisterParams) (User, error) {
	row := q.db.QueryRow(ctx, register,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name        = $2,
    description = $3,
    updated_at  = now()
WHERE id = $1 RETURNING id, name, description, workspace_id, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET stripe_price_id      = $2,
    status               = $3,
    current_period_start = $4,
    current_period_end   = $5,
    updated_at           = NOW()
WHERE stripe_subscription_id = $1 RETURNING id, workspace_id, stripe_subscription_id, stripe_price_id, status, plan, current_period_start, current_period_end, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	StripePriceID        string             `json:"stripe_price_id"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.StripeSubscriptionID,
		arg.StripePriceID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Status,
		&i.Plan,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET name        = COALESCE($1, name),
    description = COALESCE($2, description),
    start_date  = COALESCE($3, start_date),
    end_date    = COALESCE($4, end_date),
    status      = COALESCE($5, status),
    priority    = COALESCE($6, priority),
    assignee_id = COALESCE($7, assignee_id),
    updated_at  = now()
WHERE id = $8 RETURNING id, name, description, start_date, end_date, status, priority, project_id, assignee_id, created_at, updated_at
`

type UpdateTaskParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	Status      pgtype.Text `json:"status"`
	Priority    pgtype.Text `json:"priority"`
	AssigneeID  pgtype.UUID `json:"assignee_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Name,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Priority,
		&i.ProjectID,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET workspace_name = $3,
    description    = $4,
    updated_at     = now()
WHERE id = $1
  AND user_id = $2 RETURNING id, workspace_name, description, user_id, created_at, updated_at, stripe_customer_id
`

type UpdateWorkspaceParams struct {
	ID            pgtype.UUID `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
	WorkspaceName string      `json:"workspace_name"`
	Description   string      `json:"description"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.ID,
		arg.UserID,
		arg.WorkspaceName,
		arg.Description,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.WorkspaceName,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StripeCustomerID,
	)
	return i, err
}

const updateWorkspaceStripeCustomer = `-- name: UpdateWorkspaceStripeCustomer :one
UPDATE workspaces
SET stripe_customer_id = $2
WHERE id = $1 RETURNING id, workspace_name, description, user_id, created_at, updated_at, stripe_customer_id
`

type UpdateWorkspaceStripeCustomerParams struct {
	ID               pgtype.UUID `json:"id"`
	StripeCustomerID pgtype.Text `json:"stripe_customer_id"`
}

func (q *Queries) UpdateWorkspaceStripeCustomer(ctx context.Context, arg UpdateWorkspaceStripeCustomerParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceStripeCustomer, arg.ID, arg.StripeCustomerID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.WorkspaceName,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StripeCustomerID,
	)
	return i, err
}
